# Use root/example as user/password credentials
version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes: 
      - .:/usr/src/app
    depends_on: 
      - adminer
      - db
    environment: 
      - HOST_DB=db
    command: npm run dev

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./MySQL/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on: 
      - db